<?php

declare(strict_types=1);

// SPDX-FileCopyrightText: Chen Asraf <contact@casraf.dev>
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace OCA\Pantry\Service;

/**
 * Canonical lists of enumerated values used across the app (icon keys, color
 * palettes). The frontend mirrors these lists in TypeScript; whenever you
 * change one side make sure to update the other.
 */
class ConstantsService {
	/** Category icon keys, mirrored in src/components/CategoryPicker/categoryIcons.ts */
	public const CATEGORY_ICON_KEYS = [
		'tag',
		'food',
		'fruit',
		'vegetable',
		'bakery',
		'dairy',
		'meat',
		'fish',
		'snacks',
		'cookie',
		'drinks',
		'coffee',
		'frozen',
		'household',
		'pets',
		'baby',
		'home',
		'leaf',
		'pizza',
		// Shared with the checklist icon picker.
		'clipboard-check',
		'clipboard-list',
		'format-list-checks',
		'cart',
		'basket',
		'star',
		'heart',
		'calendar',
		'bell',
		'flag',
		'bookmark',
		'pin',
		'map-marker',
		'briefcase',
		'wrench',
		'silverware',
		'gift',
		'book',
		'school',
		'palette',
		'camera',
		'music',
		'gamepad',
		'run',
		'dumbbell',
		'pill',
		'paw',
		'flower',
		'tree',
		'broom',
		'lightbulb',
		'package',
		'car',
		'bike',
		'beach',
		// Pantry locations and appliances.
		'fridge',
		'freezer',
		'cupboard',
		'pantry',
		'cellar',
		'garage',
		'bookshelf',
		'locker',
		'safe',
		'file-cabinet',
		'microwave',
		'stove',
		'toaster-oven',
		'coffee-maker',
		'kettle',
		'pot',
	];

	/** Default category color palette, mirrored in the frontend. */
	public const CATEGORY_COLORS = [
		'#ef4444',
		'#f97316',
		'#eab308',
		'#22c55e',
		'#14b8a6',
		'#0ea5e9',
		'#6366f1',
		'#a855f7',
		'#ec4899',
		'#78716c',
	];

	/** Label icon keys, mirrored in src/components/LabelPicker/labelIcons.ts */
	public const LABEL_ICON_KEYS = [
		'tag',
		'tag-multiple',
		'tag-heart',
		'tag-plus',
		'label',
		'label-multiple',
		'star',
		'heart',
		'fire',
		'flash',
		'lightning-bolt',
		'priority-high',
		'priority-low',
		'alert',
		'alert-circle',
		'information',
		'check-circle',
		'close-circle',
		'clock',
		'calendar',
		'bell',
		'flag',
		'bookmark',
		'pin',
		'map-marker',
		'gift',
		'sale',
		'percent',
		'currency-usd',
		'cart',
		'basket',
		'truck',
		'ticket',
		'barcode',
		'seal',
		'leaf',
		'sprout',
		'recycle',
		'snowflake',
		'water',
		'food-apple',
		'silverware',
		'cup',
		'pill',
		'medical-bag',
		'paw',
		'baby',
		'home',
		'briefcase',
		'school',
		'palette',
		'music',
		'camera',
		'gamepad',
		'run',
		'dumbbell',
		'wrench',
		'new-box',
		'sticker',
		'thumb-up',
		'eye',
		'lock',
		'key',
		'shield',
		'diamond',
		'crown',
		'rocket',
		'bug',
		'puzzle',
		'feather',
		'bullhorn',
		'creation',
		'star-shooting',
	];

	/** Default label color palette, mirrored in the frontend. */
	public const LABEL_COLORS = [
		'#ef4444',
		'#f97316',
		'#f59e0b',
		'#eab308',
		'#84cc16',
		'#22c55e',
		'#10b981',
		'#14b8a6',
		'#06b6d4',
		'#0ea5e9',
		'#3b82f6',
		'#6366f1',
		'#8b5cf6',
		'#a855f7',
		'#d946ef',
		'#ec4899',
		'#f43f5e',
		'#78716c',
	];

	/** Store icon keys, mirrored in src/components/StoreMultiPicker/storeIcons.ts */
	public const STORE_ICON_KEYS = [
		'store',
		'storefront',
		'market',
		'supermarket',
		'convenience',
		'cart',
		'basket',
		'shopping',
		'online',
		'warehouse',
		'pharmacy',
		'health',
		'bakery',
		'butcher',
		'seafood',
		'produce',
		'garden',
		'florist',
		'hardware',
		'tools',
		'wrench',
		'electronics',
		'phone',
		'clothing',
		'shoes',
		'furniture',
		'homegoods',
		'home',
		'books',
		'toys',
		'pets',
		'liquor',
		'coffee',
		'gas',
		'gift',
		'jewelry',
		'sports',
		'beauty',
		'office',
		'baby',
		'deli',
	];

	/** Default store color palette, mirrored in the frontend. */
	public const STORE_COLORS = [
		'#e11d48',
		'#ea580c',
		'#ca8a04',
		'#16a34a',
		'#0891b2',
		'#2563eb',
		'#7c3aed',
		'#c026d3',
		'#db2777',
		'#57534e',
	];

	/** Checklist icon keys, mirrored in src/components/ChecklistIconPicker/checklistIcons.ts */
	public const CHECKLIST_ICON_KEYS = [
		'clipboard-check',
		'clipboard-list',
		'format-list-checks',
		'cart',
		'basket',
		'star',
		'heart',
		'home',
		'calendar',
		'bell',
		'flag',
		'bookmark',
		'pin',
		'map-marker',
		'briefcase',
		'wrench',
		'silverware',
		'coffee',
		'gift',
		'book',
		'school',
		'palette',
		'camera',
		'music',
		'gamepad',
		'run',
		'dumbbell',
		'pill',
		'paw',
		'flower',
		'tree',
		'broom',
		'lightbulb',
		'package',
		'car',
		'bike',
		'beach',
		'tag',
		// Pantry locations and appliances.
		'fridge',
		'freezer',
		'cupboard',
		'pantry',
		'cellar',
		'garage',
		'bookshelf',
		'locker',
		'safe',
		'file-cabinet',
		'microwave',
		'stove',
		'toaster-oven',
		'coffee-maker',
		'kettle',
		'pot',
	];

	/** Default note color palette, mirrored in src/components/Notes/noteColors.ts */
	public const NOTE_COLORS = [
		'#f44336',
		'#e91e63',
		'#9c27b0',
		'#673ab7',
		'#3f51b5',
		'#2196f3',
		'#03a9f4',
		'#00bcd4',
		'#009688',
		'#4caf50',
		'#8bc34a',
		'#cddc39',
		'#ffeb3b',
		'#ffc107',
		'#ff9800',
		'#ff5722',
	];

	/**
	 * @return array{
	 *     categoryIcons: list<string>,
	 *     categoryColors: list<string>,
	 *     labelIcons: list<string>,
	 *     labelColors: list<string>,
	 *     storeIcons: list<string>,
	 *     storeColors: list<string>,
	 *     checklistIcons: list<string>,
	 *     noteColors: list<string>,
	 * }
	 */
	public function all(): array {
		return [
			'categoryIcons' => self::CATEGORY_ICON_KEYS,
			'categoryColors' => self::CATEGORY_COLORS,
			'labelIcons' => self::LABEL_ICON_KEYS,
			'labelColors' => self::LABEL_COLORS,
			'storeIcons' => self::STORE_ICON_KEYS,
			'storeColors' => self::STORE_COLORS,
			'checklistIcons' => self::CHECKLIST_ICON_KEYS,
			'noteColors' => self::NOTE_COLORS,
		];
	}
}
